# .cpanel.yml - Simplified for Node.js App
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/maroseff/public_html/marcreator/
    - /bin/cp -R * $DEPLOYPATH
    - echo "✅ Files deployed - Node.js App handles npm install"