---
deployment:
  tasks:
    - export DEPLOYPATH=/home/maroseff/public_html/marcreator-bot/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -R .env $DEPLOYPATH || true
    - cd $DEPLOYPATH
    - /opt/alt/alt-nodejs14/root/usr/bin/npm install --production
    - echo "✅ MarCreatorBot deployed to /marcreator-bot successfully"