---
deployment:
  tasks:
    - export DEPLOYPATH=/home/maroseff/public_html/botomics-bot/
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R database $DEPLOYPATH
    - /bin/cp -R scripts $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp .env $DEPLOYPATH || true
    - echo "✅ Files deployed. Node modules will be installed by cPanel"